from serial import Serial
from time import sleep

ser = Serial('/dev/ttyACM0')
sleep(2)
ser.write(b'S')
ser.write(b'180')
sleep(0.5)
ser.write(b'S')
ser.write(b'175')
sleep(0.5)
ser.write(b'S')
ser.write(b'180')
sleep(0.5)
ser.write(b'S')
ser.write(b'175')
sleep(0.5)
ser.write(b'S')
ser.write(b'180')
sleep(2)
ser.write(b'S')
ser.write(b'100')
